/*
 * LCD_Config.h
 *
 * Created: 3/19/2022 3:58:41 AM
 *  Author: Ahmed
 */ 


#ifndef LCD_CONFIG_H_
#define LCD_CONFIG_H_

/*Function Set*/

/*LCD MODE			EIGHT_BIT_MODE		or		FOUR_BIT_MODE*/
#define DL_LCD_MODE	FOUR_BIT_MODE
/*DISPLAY_LINES		SINGLE_LINE_MODE	or		DOUBLE_LINE_MODE*/
#define N_DISPLAY_LINES	DOUBLE_LINE_MODE
/*DISPLAY_FONT		FIVE_x7	or		FIVE_x11*/
#define F_DISPLAY_FONT	FIVE_x7

/*DISPLAY Control*/
/*DISPLAY_MODE		DISPLAY_ON		or		DISPLAY_OFF*/
#define D_DISPLAY_MODE	DISPLAY_ON
/*CURSOR_MODE		CURSOR_ON		or		CURSOR_OFF*/
#define C_CURSOR_MODE		CURSOR_OFF
/*BLINK_MODE		BLINK_ON		or		BLINK_OFF*/
#define B_BLINK_MODE		BLINK_OFF

/*Entry Mode Set*/
/*INCREMENT_MODE		INCREMENT		or		DECREMENT*/
#define ID_INCREMENT_MODE		INCREMENT
/*SHIFT_MODE		NO_DISPLAY_SHIFT		or		DISPLAY_SHIFT*/
#define SH_SHIFT_MODE		NO_DISPLAY_SHIFT


/*Commands List*/
#define COM_CLEAR_DISPLAY						0x01
#define COM_RETURN_HOME							0x02
#define COM_DECREMENT_CURSOR					0x04
#define COM_INCREMENT_CURSOR					0x06
#define COM_SHIFT_DISPLAY_RIGHT					0x05
#define COM_SHIFT_DISPLAY_LEFT					0x07
#define COM_DISPLAY_OFF_CURSOR_OFF				0x08
#define COM_DISPLAY_OFF_CURSOR_ON				0x0A
#define COM_DISPLAY_ON_CURSOR_OFF				0x0C
#define COM_DISPLAY_ON_CURSOR_BLINK				0x0E
#define COM_DISPLAY_ON_CURSOR_BLINK2			0x0F
#define COM_SHIFT_CURSOR_LEFT					0x10
#define COM_SHIFT_CURSOR_RIGHT					0x14
#define COM_SHIFT_ENTIRE_DISPLAY_RIGHT			0x1C
#define COM_SHIFT_ENTIRE_DISPLAY_LEFT			0x18
#define COM_FORCE_CURSOR_1ST_LINE_1ST_POSITION	0x80
#define COM_FORCE_CURSOR_2ND_LINE_1ST_POSITION	0xC0
#define COM_2LINES_FIVE_X_7_4BIT				0x28
#define COM_2LINES_FIVE_X_7_8BIT				0x38



#define DATA_PATTERN0		0
#define DATA_PATTERN1		1
#define DATA_PATTERN2		2
#define DATA_PATTERN3		3
#define DATA_PATTERN4		4
#define DATA_PATTERN5		5
#define DATA_PATTERN6		6
#define DATA_PATTERN7		7


#endif /* LCD_CONFIG_H_ */