/*
 * TIMER1_Config.h
 *
 * Created: 4/7/2022 10:14:51 PM
 *  Author: Ahmed
 */ 


#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_
/*TIMER Mode*/
/*NORMAL		CTC	*/
#define TIMER1_MODE		NORMAL
/*PWM Mode*/
/*PWM_PHASE_CORRECT		FAST_PWM*/
#define PWM1_MODE		FAST_PWM

/*Compare Output Mode*/
/*NON	FAST	PHASE_CORRECT*/
#define COMPARE_OUTPUT_CHANNEL	A
#define COMPARE_OUTPUT_MODE			NORMAL

/*NON PWM OC1 Mode*/
/*NORMAL	TOGGLE		CLEAR		SET*/
#define NPWM_OC1_CHANNEL	A
#define NPWM_OC1_MODE	NORMAL

/*PWM OC0 Mode*/
/*NORMAL	INVERTED		NON_INVERTED*/
#define PWM_OC1_MODE	INVERTED

/*Clock Select*/
/*STOP	NO_PRESCALE		PRESCALE_8		PRESCALE_64		PRESCALE_256	PRESCALE_1024	EXTERNAL_FALLING	EXTERNAL_RISING*/
#define CLK		PRESCALE_1024
#define PRESCALE	1024UL





#endif /* TIMER1_CONFIG_H_ */