/*
 * TIMER0_Config.h
 *
 * Created: 4/5/2022 8:11:23 PM
 *  Author: Ahmed
 */ 


#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_
/*TIMER Mode*/
/*NORMA		CTC	*/
#define TIMER0_MODE		CTC
/*PWM Mode*/
/*PWM_PHASE_CORRECT		FAST_PWM*/
#define PWM0_MODE		FAST_PWM

/*Compare Output Mode*/
/*NON	FAST	PHASE_CORRECT*/
#define COMPARE_OUTPUT_MODE	NORMAL

/*NON PWM OC0 Mode*/
/*NORMAL	TOGGLE		CLEAR		SET*/
#define NPWM_OC0_MODE	NORMAL

/*PWM OC0 Mode*/
/*NORMAL	INVERTED		NON_INVERTED*/
#define PWM_OC0_MODE	INVERTED

/*Clock Select*/
/*STOP	NO_PRESCALE		PRESCALE_8		PRESCALE_64		PRESCALE_256	PRESCALE_1024	EXTERNAL_FALLING	EXTERNAL_RISING*/
#define CLK		PRESCALE_1024
#define PRESCALE	1024UL


#endif /* TIMER0_CONFIG_H_ */